name: Build and Deploy Go App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir la imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ciberegaliz/radar:latest

      - name: Desplegar en el VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Navegar al directorio específico de la aplicación radar
            # Este directorio y su docker-compose.yml son gestionados por Ansible.
            cd /srv/radar
            
            # 2. Descargar la última versión de la imagen desde Docker Hub
            # docker-compose pull solo descarga las imágenes que han cambiado.
            docker-compose pull
            
            # 3. Relanzar los servicios definidos en docker-compose.yml
            # Docker Compose es inteligente y solo reiniciará el contenedor 'radar_app'
            # si su imagen ('ciberegaliz/radar:latest') ha sido actualizada.
            docker-compose up -d